"""Original Spanish narrative. Each row is an authored playable chapter, not a synopsis slot.

Fields: title, objective, landscape, antagonist, opening, ally, protagonist, resolution.
SPDX-License-Identifier: GPL-2.0-or-later
"""

CAMPAIGNS = [
dict(key='alba', title='La última luz de Valdara', hero='Alba', companion='Oren',
     companion_type='Merman Fighter', race='human', recruit='Spearman,Bowman,Footpad,Merman Fighter,Mage',
     enemy='outlaws', length='Breve · 3 escenarios · 1–2 horas',
     premise='Alba mantiene el faro de una ciudad que ya no figura en los mapas. Cuando llegan barcos sin tripulación, deberá elegir qué significa salvar su hogar: conservar sus muros o proteger a quienes viven en él.',
     ending='Valdara desapareció bajo el agua. Sus habitantes fundaron un puerto sin murallas y encendieron una lámpara por cada persona rescatada. Alba conservó su oficio: guiar a otros hacia una costa que aún no conocían.',
     chapters=[
('Las barcas vacías','rescue','coast','Sarel, el cobrador',
 'La campana del faro sonó a mediodía, aunque Alba había retirado su badajo. En la playa aparecieron barcas vacías y, en sus bancos, nombres de vecinos todavía vivos. Los hombres de Sarel cerraron el embarcadero para cobrar por la huida.',
 'Mi hermana está encerrada en la aduana. Dice Sarel que una deuda pesa más que una vida.',
 'Abriremos esa puerta. Después discutiremos cuánto pesa su libro de cuentas.',
 'La cautiva llevaba una tablilla robada: la marea subiría antes del amanecer. No era una profecía; alguien había abierto las compuertas del arrecife.'),
('Tres fuegos en la niebla','beacons','coast','Velkan, guardacostas',
 'Para que los pescadores encontraran a las familias evacuadas, había que encender tres señales sobre los acantilados. Velkan había vendido el aceite del faro y ahora perseguía a los testigos de su trato.',
 'El aceite alcanza para tres fuegos pequeños. No para una hoguera que vean los señores desde sus torres.',
 'Las señales son para las barcas, Oren. Nunca fueron para los señores.',
 'Tres luces respondieron desde el mar. Oren reconoció el ritmo de los golpes de remo de su familia. Quedaba una última noche que comprarles.'),
('El amanecer prestado','survive','harbor','Sarel, sin puerto',
 'El agua lamía los peldaños de la plaza. Sarel regresó con mercenarios: pretendía recuperar sus pagarés antes de que la ciudad se hundiera. Alba instaló su última defensa junto a las barcas cargadas.',
 'Ya no queda sitio para la lámpara grande. Si la llevamos, alguien tendrá que quedarse.',
 'Entonces la dejamos encendida. Que la ciudad haga una última cosa buena.',
 'Cuando la última barca salió, Alba apagó la lámpara con agua de mar. Nadie le pidió que salvara las piedras.')]),

dict(key='sira', title='Los que escuchan la piedra', hero='Sira de las Siete Vetas', companion='Tarek del Eco',
     companion_type='CBM Litario Resonador', race='cbm_litario',
     recruit='CBM Litario Guardian,CBM Litario Resonador,CBM Litario Tejedor,CBM Litario Explorador',
     enemy='loyalists', length='Corta · 5 escenarios · 2–4 horas',
     premise='Los litarios nacen cuando una montaña aprende a recordar. Sira, joven portadora de siete memorias incompatibles, debe salvar las cámaras de nacimiento de su pueblo sin convertirse en la voz única que su consejo exige.',
     ending='El consejo dejó de hablar desde un solo pedestal. Cada cámara eligió a su portavoz y ninguna veta fue cerrada por disentir. Sira no fundó una dinastía: enseñó a escuchar el silencio entre dos respuestas.',
     chapters=[
('La primera grieta','escape','cave','Capataz Edran',
 'La perforadora abrió una grieta en la cámara donde Sira despertaba. Los mineros creyeron haber encontrado estatuas. Solo cambiaron de opinión cuando una de ellas apartó del derrumbe a un niño humano.',
 'Si golpeamos sus herramientas, oirán una amenaza. Si no lo hacemos, no volveremos a oír a los nuestros.',
 'Abriremos un camino hasta la cámara del eco. Quien baje el pico podrá marcharse.',
 'Tras la puerta de basalto, Sira oyó cientos de voces muy débiles. Los nacimientos se estaban apagando.'),
('Nombres bajo el martillo','rescue','quarry','Inspectora Nes',
 'Los extractores habían numerado a los litarios cautivos según la pureza de sus vetas. Entre ellos estaba el guardián que recordaba el nombre de la montaña antes de que existieran los reinos humanos.',
 'En la lista no aparece mi maestro. Solo una pieza de cuarenta arrobas.',
 'Lo llamaremos por su nombre hasta que estas paredes lo recuerden.',
 'El guardián explicó que el consejo había autorizado la extracción a cambio de herramientas. Los contratos no distinguían la piedra dormida de la que soñaba.'),
('El consejo inmóvil','beacons','cave','Custodio de la Veta Única',
 'El consejo selló los resonadores para que nadie escuchara sus pactos. Sira necesitaba despertar los tres archivos públicos. Sus custodios juraban que la obediencia era la única forma de conservar la memoria.',
 'Uno de tus siete recuerdos pertenece al consejero que firmó. ¿Cómo lucharás contra ti misma?',
 'Recordar un error no me obliga a repetirlo.',
 'Las cámaras oyeron el contrato completo. Algunas voces pidieron venganza; otras, ayuda para sacar a los humanos atrapados en las galerías.'),
('El peso de los vivos','escort','quarry','Ingeniero Voss',
 'Voss intentó inundar las minas para borrar sus cuentas. Una aprendiz humana conocía la válvula de emergencia. Transportarla por las galerías abiertas dividió a los litarios que acababan de liberarse.',
 'Nos han vendido por peso. Ahora arriesgamos las vetas por alguien que apenas pesa nada.',
 'El peso nunca fue la medida correcta.',
 'La aprendiz cerró la válvula y entregó a cada cámara una copia de los planos. Por primera vez, los litarios pudieron decidir qué puertas abrir.'),
('Una montaña, muchas voces','survive','cave','Mariscal del Diezmo',
 'El mariscal llegó para confiscar las minas. Sira distribuyó los resonadores entre las cámaras: debían mantenerlos cantando hasta que la montaña cerrara sus accesos militares, dejando libres los caminos de intercambio.',
 'Podrías ordenar un solo canto. Sería más fuerte.',
 'Sería más fácil de romper. Que cada cámara conserve su voz.',
 'El ejército se retiró cuando sus máquinas quedaron encajadas en pasos demasiado estrechos. En el valle, una puerta pequeña siguió abierta para los visitantes sin cadenas.')]),

dict(key='iria', title='La deuda del cielo', hero='Iria Salcedo', companion='Belis',
     companion_type='Elvish Shaman', race='human', recruit='Elvish Fighter,Elvish Archer,Elvish Shaman,Scout,Mage',
     enemy='velarios', length='Media · 7 escenarios · 4–6 horas',
     premise='Una sombra borra los campos de los mapas de Iria. Los velarios, seres alados de quitina nacarada, cosechan la luz para sostener sus ciudades suspendidas. Cada victoria de la cartógrafa acerca esas ciudades a una caída sobre los pueblos que quiere proteger.',
     ending='Los velarios desmontaron sus ciudades antes de que cayeran. Iria dibujó caminos entre pueblos que hasta entonces solo se habían conocido como sombras. En el margen dejó espacio para los nombres que aún faltaban.',
     chapters=[
('Un mediodía negro','survive','forest','Recolectora Thess',
 'Iria descubrió que la tinta de su mapa se secaba antes que el trigo. Una estructura alada tapaba el sol y guerreros de cuatro brazos descendían a buscar los cristales de los molinos.',
 'Las raíces sienten frío. No es una nube: alguien está llevándose el día.',
 'Resistiremos hasta evacuar a los segadores. Luego dibujaré de dónde viene esa sombra.',
 'Una lanza rota conservaba luz en su interior. Belis oyó un corazón al acercarla a una semilla.'),
('Los molinos sin sombra','beacons','plains','Custodio Oth',
 'Tres molinos concentraban la cosecha de luz. Iria decidió desconectar sus prismas antes de atacar la estructura suspendida. Los velarios defendían cada eje como si fuera una cuna.',
 'Hay voces dentro de los cristales. Están manteniendo algo vivo.',
 'Desconectaremos los molinos sin romper los depósitos. Necesitamos respuestas, no ruinas.',
 'Al cesar el flujo, un velario aterrizó sin armas. Se llamaba Esh y llevaba una cría demasiado débil para plegar las alas.'),
('El prisionero del viento','rescue','ruins','Jueza Veyth',
 'Esh fue capturado por quienes prohibían hablar con los habitantes del suelo. En su juicio no lo acusaron de traición, sino de haber revelado que las ciudades del cielo estaban muriendo.',
 'Si lo liberamos, también tendremos que escuchar lo que no queremos oír.',
 'Un mapa que oculta la mitad del terreno solo sirve para perderse.',
 'Esh contó que los velarios habían gastado sus reservas durante una guerra lejana. El consejo prefería robar estaciones enteras antes que admitir que debían aterrizar.'),
('La garganta de las alas','escape','mountain','Acechante Uru',
 'Las patrullas aladas cerraron la garganta. Iria llevaba los planos de los anclajes solares y la promesa de Esh: si lograban llegar al observatorio, podrían bajar las ciudades lentamente.',
 'Por el aire nos ven. Por el fondo del paso no podremos correr.',
 'No hace falta correr más que sus alas. Hace falta llegar donde sus alas no quepan.',
 'Desde el observatorio, Iria vio que una ciudad ya se inclinaba. Bajo ella estaba el pueblo donde había aprendido a escribir.'),
('El pueblo que sostuvo el cielo','escort','plains','Recolectora Neth',
 'Belis encontró un cristal capaz de estabilizar la ciudad inclinada. Un transportista lo llevaría hasta el anclaje, mientras los recolectores intentaban recuperarlo para sus propios barrios.',
 'Cada calle que salvemos arriba puede costarnos una cosecha abajo.',
 'Hoy evitamos la caída. Mañana obligaremos a sus jefes a compartir esa cuenta.',
 'El anclaje resistió. Desde las plataformas bajaron cuerdas con agua y alimentos: algunos velarios habían visto quién los había salvado.'),
('La torre de los acreedores','conquer','ruins','Arconte Sesher',
 'Sesher exigió otro invierno de oscuridad a cambio de negociar. Iria reunió a quienes habían trabajado en los anclajes para tomar su torre y abrir los registros de consumo.',
 'Dirá que el cielo le pertenece porque sus antepasados lo levantaron.',
 'Entonces leerá cuántos inviernos llevan pagándolo los nuestros.',
 'Los registros mostraron que el palacio gastaba más luz que seis barrios. La guardia de Sesher abandonó sus puestos al conocer los números.'),
('Donde termina la sombra','beacons','harbor','Vigía de la Última Altura',
 'La facción que rechazaba el descenso bloqueó los tres anclajes del puerto. Iria y Belis debían sincronizarlos mientras las familias velarias esperaban sobre plataformas que crujían.',
 'Cuando aterricen, habrá menos cielo y mucha más gente en nuestros caminos.',
 'Habrá vecinos. Los mapas sirven para encontrarles sitio.',
 'Las ciudades tocaron tierra al atardecer. Nadie aplaudió al principio: todos estaban escuchando un silencio sin motores.')]),

dict(key='maura', title='El trono de ceniza', hero='Maura Vey', companion='Sevrin',
     companion_type='Deathblade', race='human', recruit='Skeleton,Skeleton Archer,Dark Adept,Ghoul,Vampire Bat',
     enemy='loyalists', length='Larga · 9 escenarios · 5–8 horas',
     premise='Encarnas a Maura Vey, una archivera que convierte la deuda de los muertos en un ejército. Sus adversarios tienen motivos para resistirse. Sus victorias construyen una tiranía, y ninguna revelación final la convierte en una heroína incomprendida.',
     ending='Maura ocupó el trono sin abolir un solo impuesto. Añadió uno: todo ciudadano debía legar su cuerpo al Estado. Sevrin pidió permiso para descansar. La reina guardó su petición en un archivo que nunca pensaba abrir.',
     chapters=[
('El archivo prohibido','beacons','ruins','Magistrado Helmor',
 'Maura descubrió que los contratos funerarios conservaban los nombres necesarios para llamar a los muertos. El magistrado ordenó quemar el archivo. Ella decidió apropiarse de sus tres sellos antes de que llegaran los alguaciles.',
 'Soy Sevrin. Firmé por una sepultura, no por otra guerra.',
 'Firmaste obediencia a quien custodiara el sello. Ahora lo custodio yo.',
 'Los muertos salieron en orden alfabético. Maura anotó la primera ventaja de su ejército: nadie preguntaba por la paga.'),
('Pan para los obedientes','conquer','plains','Capitana Arel',
 'Los graneros alimentaban a la ciudad que había expulsado a Maura. Tomarlos le permitiría comprar soldados vivos y condenar al hambre a quienes no aceptaran su protección.',
 'Hay familias dentro. Puedo romper las puertas sin prender los sacos.',
 'Conserva el grano. Necesito que sepan exactamente quién decide cuándo comen.',
 'Maura repartió raciones junto a formularios de lealtad. Los escribas registraron cada negativa.'),
('El testigo incómodo','rescue','forest','Juez Calven',
 'Un notario había descubierto cómo romper los sellos funerarios. Maura quería sacarlo de la custodia real y encerrarlo en un lugar donde solo ella pudiera hacer preguntas.',
 'Podrías dejar que publicara el método. Algunos de nosotros volveríamos a dormir.',
 'Y yo perdería un ejército. No vuelvas a confundir tus deseos con mis intereses.',
 'El notario llegó vivo a la torre. Maura quemó sus notas después de aprenderlas de memoria.'),
('La calzada del tributo','escort','mountain','Guardiana Derra',
 'Un carro transportaba los sellos arrebatados al notario. Los pueblos de la calzada intentaron detenerlo antes de que Maura pudiera reclamar a sus antepasados.',
 'Nos arrojan piedras con los nombres de los que llevamos encadenados.',
 'Recógelas. Facilitarán el próximo inventario.',
 'El carro cruzó el paso. Detrás quedó una calzada donde ya nadie enterraba a sus muertos con nombre.'),
('La noche de los juramentos','survive','ruins','General Vaust',
 'El general atacó mientras Maura vinculaba a su sello central los contratos robados. Romper el círculo antes del amanecer devolvería la libertad a miles de muertos.',
 'Aún puedes detener el ritual. Nadie te obligó a llegar hasta aquí.',
 'Lo sé. Por eso esta corona será mía.',
 'Al amanecer, el ejército entero giró hacia Maura al mismo tiempo. Sevrin intentó quedarse quieto y no pudo.'),
('Las tres campanas','beacons','harbor','Abadesa Ysol',
 'Las campanas del santuario liberaban a los muertos que oían su repique. Maura ordenó silenciarlas antes de entrar en la capital. Los defensores dejaron abiertas las puertas para quienes huyeran de ella.',
 'Incluso ahora nos ofrecen refugio.',
 'Ofrecen deserción. Desmonta las campanas y funde sus badajos.',
 'El bronce del santuario se convirtió en clavos para la puerta del palacio.'),
('El precio de una tregua','conquer','forest','Embajadora Nalis',
 'Una liga de villas ofreció reconocer a Maura si liberaba a sus caídos. Ella acudió a la negociación con el ejército desplegado: aceptaría el reconocimiento, pero no devolvería nada.',
 'Podrías ganar una paz duradera con una sola firma.',
 'Una paz que dependa de mi generosidad termina cuando deje de ser generosa.',
 'Las villas firmaron bajo vigilancia. Maura conservó el documento como prueba de su legitimidad.'),
('La puerta sin retorno','escape','cave','Paladín Eron',
 'La última defensa de la capital derrumbó el túnel que Maura utilizaba para infiltrarse. La reina aspirante debía alcanzar la cisterna interior antes de que sus perseguidores sellaran la salida.',
 'Arriba luchan por sus hijos. Aquí abajo, ¿por quién luchamos nosotros?',
 'Tú luchas porque te lo ordeno. Yo, porque todavía hay alguien capaz de decirme que no.',
 'Maura emergió en la cisterna y abrió las compuertas para su ejército. El agua de la ciudad dejó de correr.'),
('Una corona sin herederos','conquer','ruins','Regente Alther',
 'Alther ofreció abdicar si Maura garantizaba la libertad de los muertos. Ella rechazó el trato ante ambos ejércitos. Quería una victoria que nadie pudiera confundir con un acuerdo.',
 'Cuando ya no quede nadie por conquistar, ¿nos dejarás descansar?',
 'Un reino siempre necesita guardianes.',
 'El regente cayó. Maura ordenó que lo incorporaran a la guardia del trono antes de limpiar la sala.')]),

dict(key='nerea', title='Las mareas sin nombre', hero='Nerea Vado', companion='Luar',
     companion_type='Merman Hunter', race='human', recruit='Merman Fighter,Merman Hunter,Mermaid Initiate,Footpad,Bowman,Mage',
     enemy='nagas', length='Muy larga · 12 escenarios · 8–12 horas',
     premise='Una capitana de puerto libre y un cazador del arrecife siguen una corriente que borra los nombres de las islas. Doce travesías los enfrentarán a contrabandistas, custodios naga y una máquina que transforma la memoria en mareas.',
     ending='Las islas recuperaron nombres elegidos por sus habitantes. Nerea fundó una escuela de navegación donde el primer mapa se dibujaba escuchando a otro. Luar escribió el suyo bajo el agua, para que nadie pudiera llevárselo sin aprender a bucear.',
     chapters=[
('El puerto sin cartas','rescue','harbor','Recaudadora Vaska',
 'Todos los nombres desaparecieron de las cartas del puerto. Vaska arrestó al único piloto que aún recordaba la salida y vendió permisos de navegación imposibles de usar.',
 'La corriente recuerda rutas que vuestra tinta ha olvidado.',
 'Entonces llevaremos al piloto hasta tu corriente y cobraremos la ayuda en respuestas.',
 'El piloto recordó una isla que había desaparecido de los registros tres años antes de hundirse.'),
('Los dientes del arrecife','escape','coast','Naga Kess',
 'El paso exterior estaba custodiado por guerreros naga. Sus lanzas señalaban hacia el puerto, como si quisieran impedir que algo saliera de él.',
 'No protegen un tesoro. Están cerrando una herida.',
 'Crucemos sin quedarnos atrapados entre sus lanzas y la marea.',
 'Al otro lado del arrecife, el mar tenía el sabor del agua de lluvia.'),
('Agua dulce en mar abierto','beacons','islands','Custodio Issar',
 'Tres fuentes sumergidas vertían agua dulce desde una isla invisible. Activar sus balizas antiguas mostraría el camino, pero Issar había prohibido tocar los mecanismos.',
 'Mi abuela hablaba de manantiales que pagaban su caudal con recuerdos.',
 'Hoy solo les pediremos una dirección.',
 'Las balizas revelaron una calzada bajo la superficie. Sobre sus piedras estaban grabados nombres tachados.'),
('La isla borrada','conquer','ruins','Almirante Serkos',
 'Serkos utilizaba la isla sin nombre para ocultar barcos confiscados. Entre sus prisioneros había familias que el resto del mundo había olvidado por completo.',
 'Si regresan y nadie los reconoce, ¿adónde podrán ir?',
 'Primero abrimos las puertas. Luego haremos sitio.',
 'Una niña reconoció a Nerea en un retrato viejo. La capitana no recordaba haber visitado aquella isla.'),
('El cuaderno de otra vida','escort','forest','Rastreadora Olss',
 'La niña conservaba un cuaderno escrito por la madre de Nerea. Debían llevarlo a la casa de mareas, donde una lectora ciega podía descifrar la tinta que solo aparecía al anochecer.',
 'Puedes abrirlo ahora. Nadie te culparía.',
 'Si la tinta se borra al sol, mi impaciencia volverá a dejarla sin voz.',
 'La lectora encontró una orden de emergencia: la madre de Nerea había borrado una ruta para detener una invasión.'),
('Quienes pagan la calma','survive','islands','Primera Lanza Uss',
 'Los custodios naga exigieron entregar el cuaderno. Cada noche que la máquina mantenía tranquilas las aguas borraba un recuerdo de las islas periféricas. La madre de Nerea había intentado detenerla.',
 'La calma de vuestro puerto nos ha costado generaciones enteras.',
 'No pediré que nos perdonéis. Dame esta noche para sacar a la gente de su alcance.',
 'Los isleños huyeron con canciones repetidas en voz alta para no olvidar a quienes viajaban en la barca de al lado.'),
('El mercado de los nombres','rescue','harbor','Mercader Dorven',
 'Dorven comerciaba con tablillas capaces de conservar recuerdos. Una buceadora cautiva conocía la entrada de la máquina; el mercader la vendía junto con el nombre de su familia.',
 'Podemos pagar. Llevas oro suficiente.',
 'Y mañana venderá a otra. Hoy se termina su negocio.',
 'La buceadora enseñó a Luar una ruta por las cámaras inundadas. A cambio pidió que nadie volviera a escribir un precio junto a su nombre.'),
('Las compuertas del olvido','beacons','cave','Guardián de la Sal',
 'Las tres compuertas distribuían la memoria robada. Abrirlas a la vez devolvería parte de ella, pero también liberaría a los centinelas que la máquina alimentaba.',
 'Si escuchas a tu madre, no sigas su voz. Será un recuerdo buscando salida.',
 'La escucharé. Y seguiré andando.',
 'Miles de nombres salieron con el agua. Nerea recordó unas manos enseñándole a hacer un nudo.'),
('La flota de nadie','conquer','coast','Serkos, sin bandera',
 'Serkos reunió los barcos abandonados para apoderarse del mecanismo. Prometía mares tranquilos a quienes aceptaran olvidar la guerra que él mismo había iniciado.',
 'Hay capitanes dispuestos a creerle. Están cansados.',
 'Les ofreceremos un puerto al que volver sin entregar su pasado.',
 'La flota se rindió cuando sus tripulantes recordaron quién había confiscado sus barcos.'),
('Un camino para los naga','escort','islands','Custodia Eshka',
 'Una emisaria naga aceptó guiar a los isleños hasta el núcleo. Eshka, defensora de la vieja ley, prefería hundir los pasos antes que permitir que manos extranjeras los cruzaran.',
 'La emisaria ha perdido más nombres que nosotros. Y aun así recuerda cómo confiar.',
 'No caminaremos delante de ella como conquistadores. Le cubriremos la espalda.',
 'Al llegar, la emisaria entregó una llave hecha de conchas. Cada concha representaba una comunidad que había aceptado apagar la máquina.'),
('El último mar en calma','survive','ruins','Centinela del Núcleo',
 'Apagar el núcleo exigía mantener sus válvulas abiertas durante un ciclo completo. Los centinelas interpretaron la maniobra como una avería y atacaron a quienes la ejecutaban.',
 'Después habrá tormentas. No podremos prometer que todos regresen de cada viaje.',
 'Podremos prometer que los recordaremos.',
 'El núcleo se enfrió. Por primera vez en décadas, una ola rompió sin obedecer a una máquina.'),
('Nombres sobre el agua','escape','harbor','Último Custodio',
 'Las galerías se inundaron cuando regresó la marea natural. El último custodio quiso retener a Nerea para reiniciar el mecanismo. Las barcas aguardaban más allá de los muelles partidos.',
 'Tu madre dejó una salida en los planos. La dibujó incluso cuando pensaba quedarse.',
 'Entonces la usaremos. Su historia no tiene que terminar dos veces igual.',
 'Nerea salió a un mar difícil y libre. En el cuaderno escribió el nombre de cada persona que había vuelto con ella.')]),

dict(key='darian', title='El pacto de las siete brasas', hero='Darian de Linde', companion='Ena',
     companion_type='White Mage', race='human', recruit='Spearman,Bowman,Mage,Elvish Fighter,Elvish Shaman',
     enemy='undead', length='Épica · 16 escenarios · 12–18 horas',
     premise='Un correo transporta siete cartas para pueblos que no confían entre sí. Mientras el imperio de Maura reclama vivos y muertos, Darian debe construir una alianza entre puertos libres, litarios, velarios y antiguos enemigos. Se puede jugar sin completar las otras cinco campañas.',
     ending='Las siete brasas no se fundieron en una corona. Cada pueblo conservó una, y el pacto exigía que cualquier decisión pudiera ser rechazada. Darian volvió al camino con una bolsa más ligera: por primera vez llevaba respuestas en vez de ultimátums.',
     chapters=[
('Siete cartas, ningún rey','escape','forest','Recaudador de Ceniza',
 'Darian salió de Linde con siete cartas y un caballo que perdió en el primer control imperial. Las cartas proponían reunir a quienes Maura todavía no había sometido. Ninguna llevaba un sello real.',
 'Sin un rey detrás, dirán que no representamos a nadie.',
 'Representamos a quienes todavía pueden responder que no.',
 'Ena salvó las cartas de una acequia. La primera estaba dirigida a una ciudad que el mar ya se había llevado.'),
('La luz que emigró','survive','harbor','Teniente del Tributo',
 'Los supervivientes de Valdara habían construido un puerto nuevo. Alba aceptó leer la carta si Darian ayudaba a defender a los recién llegados de los cobradores de cuerpos del imperio.',
 'Alba no necesita promesas. Necesita tiempo para desembarcar familias.',
 'Entonces nuestra primera firma se ganará aquí, junto a las barcas.',
 'Alba encendió una lámpara sobre la carta: el puerto aportaría barcos y refugio, pero no aceptaría volver a ser un muro que encerrara a su gente.'),
('La puerta que escucha','beacons','mountain','Tasador de las Vetas',
 'La entrada de los litarios solo se abría cuando tres resonadores repetían una petición sin órdenes. Los tasadores imperiales rodeaban el valle para apropiarse de sus cámaras de nacimiento.',
 'Podrías exigir entrada en nombre de la alianza.',
 'Todavía no existe una alianza. Empecemos por pedir permiso.',
 'Sira abrió la puerta pequeña. Los litarios enviarían guardianes si el pacto reconocía que una montaña podía pertenecer a sus habitantes.'),
('Los hijos de la sombra','rescue','plains','Carcelero de las Alas',
 'En una ciudad velaria recién asentada, el imperio capturaba a quienes no podían volar. Darian debía liberar a una intérprete antes de presentar la tercera carta.',
 'Los campesinos recuerdan los inviernos sin luz. No todos querrán ayudarlos.',
 'No les pediremos que olviden. Les pediremos que nadie vuelva a pagar una deuda con su vida.',
 'La intérprete llevó la carta al consejo. Iria añadió un mapa donde los campos y las ciudades aladas compartían las mismas acequias.'),
('El puente de los agravios','escort','forest','Capitán Rusk',
 'Una delegada campesina aceptó cruzar el antiguo frente para negociar con los velarios. Rusk, enriquecido con la guerra, anunció que cualquier acuerdo sería una traición a los muertos.',
 'La delegada perdió a dos hermanos durante la oscuridad.',
 'Por eso es ella quien decide cruzar. Nosotros haremos que llegue.',
 'La negociación comenzó con una lista de daños y terminó con un calendario de reparaciones. Nadie lo llamó perdón.'),
('La cuarta brasa','conquer','coast','Almirante del Sello',
 'Nerea había reunido una flota de puertos libres, pero un almirante imperial cerraba la salida al estrecho. Darian necesitaba despejarlo antes de que llegaran los refugiados del interior.',
 'La capitana exige que ninguna nave de la alianza transporte cautivos.',
 'Escribámoslo antes de pedirle un solo barco.',
 'El estrecho quedó abierto. Nerea firmó con tinta común, para que cualquiera pudiera leer las condiciones.'),
('Quienes no firmaron','survive','quarry','Prefecto Arven',
 'Las canteras albergaban a desertores de ambos bandos. No querían unirse a ningún ejército. El prefecto los declaró propiedad abandonada del Estado y marchó a recogerlos.',
 'Si los defendemos, quizá se marchen sin darnos nada.',
 'Ese es el derecho que decimos defender.',
 'Los desertores no juraron lealtad. Ofrecieron herramientas, guías y un lugar donde descansar. Darian anotó la quinta brasa sin añadir un juramento.'),
('El mensajero de hueso','rescue','ruins','Custodio del Archivo',
 'Sevrin había logrado enviar una petición de auxilio desde los archivos de Maura. La guardia lo encadenó a su propio contrato para impedir otra fuga. Liberarlo revelaría cómo romper el sello central.',
 'Ha dirigido ejércitos contra todos nuestros aliados.',
 'Tendrá que responder por ello. Primero debe poder elegir sus respuestas.',
 'Sevrin entregó el nombre verdadero del sello. No pidió absolución; pidió que su testimonio incluyera todo lo que había hecho.'),
('La sal de los juramentos','beacons','islands','Vigía de las Cadenas',
 'Tres altares costeros guardaban copias de los contratos funerarios. Disolverlas en agua salada debilitaría la red de Maura. Los guardianes intentaron trasladarlas antes de la llegada de la flota.',
 'Cada sello roto libera una voz. También avisa a la reina de dónde estamos.',
 'Que escuche cuántas voces ha intentado callar.',
 'Los muertos liberados señalaron los caminos por los que eran transportados los nuevos cautivos.'),
('La sexta respuesta','escort','cave','Cazador de Deudas',
 'Una escribana de la capital traía un registro de ciudadanos condenados al servicio después de morir. Debía cruzar las galerías litarias para que cada familia pudiera impugnar su contrato.',
 'El registro pesa más que nuestras siete cartas juntas.',
 'Entonces lo llevaremos entre todos.',
 'La sexta brasa perteneció a los barrios de la capital. Su respuesta no llevaba nombres: publicarlos habría condenado a quienes seguían dentro.'),
('Un ejército de vecinos','conquer','plains','Mariscal de Ceniza',
 'El mariscal concentró sus tropas en el granero central. La alianza debía tomarlo para alimentar a los barrios rebeldes, manteniendo abiertas las rutas de quienes no participaban en la guerra.',
 'Tenemos soldados de pueblos que hace un año se atacaban entre sí.',
 'Hoy comparten una tarea. La confianza vendrá de cumplirla.',
 'Los carros de grano salieron con escoltas mezcladas. Ningún pueblo recibió permiso para decidir la ración de otro.'),
('La noche de las dos órdenes','survive','forest','Inquisidora Vael',
 'La inquisidora difundió órdenes falsas para dividir a la alianza. Darian reunió a los delegados alrededor de las brasas mientras las patrullas enemigas intentaban capturarlos por separado.',
 'Si cada contingente obedece su propia carta, no resistiremos.',
 'Que vengan y pregunten. Una orden que no admite preguntas ya nos ha hecho bastante daño.',
 'Las falsificaciones fallaron porque los delegados se conocían. La séptima brasa fue una regla: ninguna voz hablaría por todas sin poder ser contradicha.'),
('El nombre del sello','beacons','ruins','Notario Inmortal',
 'El nombre del sello estaba repartido entre tres archivos para que ningún servidor pudiera destruirlo. Sevrin recordaba sus ubicaciones. Darian debía reunir las inscripciones antes de entrar en palacio.',
 'Al romperlo, algunos de nuestros combatientes caerán. Luchan unidos a esos mismos contratos.',
 'Se lo diremos antes. Esta vez nadie decidirá por ellos.',
 'Los muertos de la alianza eligieron sostener la última marcha. Cada uno pidió algo distinto para después.'),
('La ciudad que abrió sus puertas','rescue','harbor','Gobernador de las Cenizas',
 'Los barrios se alzaron, pero el gobernador tomó rehenes en la aduana. Liberar a su portavoz permitiría abrir las puertas interiores sin arrasar la ciudad que la alianza decía venir a salvar.',
 'Los arietes llegarán antes que nosotros si tomamos el camino largo.',
 'Envía un correo para detenerlos. No hemos cruzado medio mundo para entrar sobre sus casas.',
 'La portavoz abrió las puertas desde dentro. Los vecinos guiaron a la alianza por calles donde todavía ardían las lámparas.'),
('La reina que no descansaba','conquer','ruins','Maura Vey',
 'Maura ofreció entregar provincias a cada aliado si abandonaban a los demás. Había preparado siete documentos, convencida de que cualquier pacto era una colección de ambiciones comprables.',
 'Sus ofertas son reales. Algunos podrían salvar a su pueblo marchándose ahora.',
 'Y condenar al siguiente. Hemos leído juntos la letra pequeña de demasiados contratos.',
 'Maura perdió el trono y fue llevada ante representantes de sus víctimas. Darian prohibió que su nombre se añadiera a ningún contrato funerario.'),
('La última entrega','escape','mountain','Guardián del Sello Roto',
 'El sello central debía destruirse en la montaña donde se había tallado. Sus últimos guardianes, incapaces de comprender que la reina ya no mandaba, persiguieron a Darian hasta la cámara abierta.',
 'Cuando lo destruyas, Sevrin podrá descansar. No habrá otra oportunidad de preguntarle nada.',
 'Ya dio su testimonio. No nos debe una eternidad.',
 'Darian depositó el sello entre las brasas. El último correo de la guerra fue una lista de nombres liberados, enviada a todos los pueblos sin exigir respuesta.')])
]
